project:
  type: website
  output-dir: docs

website:
  #title: # add a logal instead if possible?
# favicon: images/
  navbar:
  # title: false -> disaples for navbar but main
  # logo: images/
  # logo-alt: discribes for accsessability speech impare
    left:
      - href: main_page.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: post.qmd 
        text: Blog
      # - href: resources.qmd
      #   text: Resources
format:
  html:
    theme: lux
    #css: styles.css
    toc: true
    page-layout: full
    mainfont: Alice


