project:
  type: website
  output-dir: docs
website:
  title: "Ixel Medrano" # Defaults to github name 
  favicon: media/logo-aff.png
# add listing pages for websiteto navbar
  navbar:
    title: false # override printing your website `title` in the top left corner of your navbar
    logo: media/logo-aff.png
    logo-alt: "A logo with a cat playing with a crescent moon that connects as the letter i for ee-shells name"
    right: # accepts right/left/center; you can also place items individually on the left, right, and center
      - href: index.qmd
        text: Home # changed navbar name
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Blog
#     - href: resources.qmd 
#       text: Resources
  page-footer:
      background: light # or `dark` or omit this option altogether (footer color will match page body color)
      left: "&copy; 2025 Ixel Medrano" 
      right: This website is built with {{< fa heart title= "a heart" >}}, [{{< fa brands github title= "GitHub octocat logo" >}}](https://github.com/iidonaji/iidonaji.github.io/){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}



# web page theme/color
format:
  html:
    theme: styles.scss # can a pre define theme or to toggle between light and dark
#      light: lux
#      dark: solar
    toc: false
    page-layout: full # set to full so that page content takes up more of  the page width
#    mainfont: Alice # assign default font in all text elements on website .scss styles now
  
    
editor: visual
