project:
  type: website
  output-dir: docs
 
# ~ parts of `_quarto.yml` omitted for brevity ~
website:
  title: "Ixel Medrano" # add a logal instead if possible?
# favicon: images/
  navbar:
    #title: False #-> disaples for navbar but main
   #logo: images/
  # logo-alt: discribes for accsessability speech impare
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: posts.qmd
        text: Blog
       # add your listing page file to your navbar, just like you would any other new web page
      # - href: resources.qmd
      #   text: Resources
# supplying just one them ("lux")
format:
  html:
    theme: lux
   #css: styles.css
    toc: true
    page-layout: full
    mainfont: Alice

editor: visual
